### ISSUE TITLE
Metadata Standard Name and Version should be read-only

### ISSUE THREAD

**Issue by archaeogeek** [josegar74/generator-geonetwork-metadata-schema#1]
They are pre-filled in, in the templates, but are editable

**Comment by josegar74** [comment]
This is the same in the default `iso19139` schema, there's no xslt template to make them readonly. Creating a `iso19139` metadata in GeoNetwork, these elements are editable:

![edit-metadataschema-name-version](https://user-images.githubusercontent.com/1695003/42968768-8cf55a7c-8ba4-11e8-8682-f0fdb53630be.png)

I'll check to add the templates commented in the generated code, so if required in a schema that use these elements to relate the metadata to the schema, can be uncommented.
