### ISSUE TITLE
Plus button for distribution format in simple view doesn't work

### ISSUE THREAD

**Issue by archaeogeek** [josegar74/generator-geonetwork-metadata-schema#2]
In simple view the plus button spins and adds a blank line with no text element. In advanced view it adds the format information correctly. I think this should also be a dropdown box with helper values from the codelists rather than just a text element

**Comment by josegar74** [comment]
You mean nothing is displayed for you?

For me, the elements are added, but no labels:

![distribution-format-2](https://user-images.githubusercontent.com/1695003/42985174-8e320f60-8bf0-11e8-850f-4a827d563226.png)

I created a issue for this in GeoNetwork repository: https://github.com/geonetwork/core-geonetwork/issues/2986, seem a wrong behaviour of the table layout when adding a new element.

**Comment by archaeogeek** [comment]
Hi Jose,

Today, with a clean commit and a cache clear, and a new schema plugin generated from your newest generator, it works fine and shows me the labels:
![screenshot from 2018-07-20 10-49-20](https://user-images.githubusercontent.com/1544849/42996150-9ed55254-8c0a-11e8-985f-b1fca94d6ca3.png)

So I'm happy to close this.

Jo
